FROM condaforge/mambaforge

RUN apt-get -qq update --yes \
  && apt-get -qq install --yes --no-install-recommends \
  build-essential git make postgresql-client \
  ca-certificates wget locales \
  && rm -rf /var/lib/apt/lists/*

#Set locale
RUN sed -i -e "s/# pt_BR.*/pt_BR.UTF-8 UTF-8/" /etc/locale.gen \
  && dpkg-reconfigure --frontend=noninteractive locales \
  && update-locale LANG=pt_BR.UTF-8

# Copy environment file to tmp/
COPY crawlclima/environment.yml /tmp/environment.yml

# Use environment to update the env base
RUN conda update -n base -c defaults conda \
  && mamba update --all --yes --quiet \
  && mamba env update --file /tmp/environment.yml --name base \
  && mamba clean -afy


# Copy the script file to initialize celery
COPY crawlclima/containers/start_celery_beat.sh /start_celery_beat.sh
RUN chmod +x /start_celery_beat.sh

# Create script activate environment
RUN echo 'source /opt/conda/bin/activate base && exec "$@"' > activate.sh
RUN chmod +x /activate.sh

# Directory
ADD crawlclima /AlertaDengueCaptura/

WORKDIR /AlertaDengueCaptura/
RUN pip install -e .

ENTRYPOINT ["bash", "/activate.sh"]
CMD ["/start_celery_beat.sh"]
